### ISSUE TITLE
Image size

### ISSUE THREAD

**Issue by Ronald-Kray** [yakhyo/crackseg#4]
Have you tried different image size?
It works well on the exmaple image, but I've got an errors on different size images.

**Comment by yakhyo** [comment]
Nope, I only trained the model using image size of 448x448. I noticed that the image_size parameter was not actually used in the training process. I would recommend implementing image resizing in dataset.py file.

**Comment by yakhyo** [comment]
@Ronald-Kray , I added image resizing.
